### ISSUE TITLE
font and margins

### ISSUE THREAD

**Issue by ghost** [gilbertohasnofb/typora-whitey-dark-theme#1]
Why the font (in code block) and margins in this dark version are different from the original version?

**Comment by gilbertohasnofb** [comment]
Hi there. Although this theme is based on the default Whitey theme, I did make some alterations to the margins. Also, I do use a different font for the code in my system, and I believe the original theme was forcing a specific font, which is why I altered it a bit. The reason for both of these changes is simply that I like them better. 

If you want the margins to behave exactly as in the default Whitey theme, there's a simple edit you can make in the file whitey-dark.css (which should be located in your themes folder).  Look for lines 190--208 (shown below)...:

```
#write {
	max-width: 800px;
	margin: 0 auto;
	margin-bottom: 2em;
	line-height: 1.53;
	padding-top: 40px;
}

@media only screen and (min-width: 1400px) {
	#write {
		max-width: 800px;
	}
}

@media print {
	html {
		font-size: 13px;
	}
}
```

... and replace them with:

```
#write {
	max-width: 960px;
	margin: 0 auto;
	margin-bottom: 2em;
	line-height: 1.53;
}
```

=====

As for the font, try doing these changes:

1) Replace the contents of both lines 31 and 436 from...:

```
    font-family: monospace;
```

... with:

``` 
    font-family: Courier, monospace;
```

2) Replace line 285 from...:

```
    font-size: .8em;
```

... with:

``` 
    font-family: "Consolas", "Menlo", "Monaco", monospace, serif;
    font-size: .9em;
```

Let me know if this works for you.

**Comment by ghost** [comment]
That works, thanks a lot!!

**Comment by gilbertohasnofb** [comment]
Happy to hear that! Enjoy the theme :smile:
